version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - ./prometheus/:/etc/prometheus/
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--web.enable-lifecycle'
    ports:
    - 9090:9090
    links:
    - alertmanager:alertmanager
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
    - 9100:9100
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
    - 9093:9093
    volumes:
    - ./alertmanager/:/etc/alertmanager/
    command:
    - '--config.file=/etc/alertmanager/config.yml'
 
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000"
    depends_on:
    - prometheus
    ports:
    - 3000:3000
    volumes:
    - ./grafana/:/var/lib/grafana
    - ./grafana/grafana.ini:/etc/grafana/grafana.ini
